{% set name = "pypickle" %}
{% set version = "1.1.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypickle-{{ version }}.tar.gz
  sha256: dd96f3622943c7673728ffd239c6b130523b475cc3753388afb3b011e9d27359

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel
  run:
    - python >={{ python_min }}

test:
  imports:
    - pypickle
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/erdogant/pypickle
  summary: Save and load variables in/from pickle files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
