{% set name = "pypickle" %}
{% set version = "1.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pypickle-{{ version }}.tar.gz
  sha256: a648fac94aa7061612159d0ffa7ad82f6f04969e1afd0403af96714867d580d8

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - pypickle
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/erdogant/pypickle
  summary: Save and load variables in/from pickle files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
