{% set name = "pypickle" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pypickle-{{ version }}.tar.gz
  sha256: 81618b685e6282c264cd5cc0af15c1f3a7ee0e364c6e59740d7b7486f728e5de

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}

test:
  imports:
    - pypickle
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/erdogant/pypickle
  summary: Save and load variables in/from pickle files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
