schema_version: 1

context:
  name: pypickle
  version: "2.0.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pypickle-${{ version }}.tar.gz
  sha256: 0cc1ee65293e4dfa90f0db6435e8021c6a83346be98d0fee81aceb2dad1fb091

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - wheel
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - pypickle
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Save and load variables in/from pickle files
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/erdogant/pypickle

extra:
  recipe-maintainers:
    - thewchan
